# Find the Leveldb includes and library

FIND_PATH(LEVELDB_INCLUDE_DIR leveldb/db.h
    /usr/local/include
    /usr/include
)

# On unix system, debug and release have the same name
FIND_LIBRARY(LEVELDB_LIBRARY leveldb
    ${LEVELDB_INCLUDE_DIR}/../lib64
    /usr/local/lib64
    /usr/lib64)

IF (LEVELDB_INCLUDE_DIR AND LEVELDB_LIBRARY)
    SET(LEVELDB_FOUND TRUE)
ENDIF (LEVELDB_INCLUDE_DIR AND LEVELDB_LIBRARY)

IF (LEVELDB_FOUND)
    MESSAGE(STATUS "Found LEVELDB INCLUDE: ${LEVELDB_INCLUDE_DIR}")
    MESSAGE(STATUS "Found LEVELDB LIBRARY: ${LEVELDB_LIBRARY}")
    SET(LEVELDB_LIBRARIES ${LEVELDB_LIBRARY})
ELSE (LEVELDB_FOUND)
    IF (LEVELDB_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "LEVELDB not found")
    ELSE (LEVELDB_FIND_REQUIRED)
        MESSAGE(STATUS "LEVELDB not found")
    ENDIF (LEVELDB_FIND_REQUIRED)
ENDIF (LEVELDB_FOUND)

MARK_AS_ADVANCED(LEVELDB_INCLUDE_DIR LEVELDB_LIBRARY)

