# Find the Gflags includes and library

FIND_PATH(GFLAGS_INCLUDE_DIR gflags/gflags.h
    /usr/local/include
    /usr/include
)

# On unix system, debug and release have the same name
FIND_LIBRARY(GFLAGS_LIBRARY gflags
    ${GFLAGS_INCLUDE_DIR}/../lib64
    /usr/local/lib64
    /usr/lib64)

IF (GFLAGS_INCLUDE_DIR AND GFLAGS_LIBRARY)
    SET(GFLAGS_FOUND TRUE)
ENDIF (GFLAGS_INCLUDE_DIR AND GFLAGS_LIBRARY)

IF (GFLAGS_FOUND)
    MESSAGE(STATUS "Found GFLAGS INCLUDE: ${GFLAGS_INCLUDE_DIR}")
    MESSAGE(STATUS "Found GFLAGS LIBRARY: ${GFLAGS_LIBRARY}")
    SET(GFLAGS_LIBRARIES ${GFLAGS_LIBRARY})
ELSE (GFLAGS_FOUND)
    IF (GFLAGS_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "GFLAGS not found")
    ELSE (GFLAGS_FIND_REQUIRED)
        MESSAGE(STATUS "GFLAGS not found")
    ENDIF (GFLAGS_FIND_REQUIRED)
ENDIF (GFLAGS_FOUND)

MARK_AS_ADVANCED(GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY)
