# Find the LibEvent includes and library

FIND_PATH(LIBEVENT_INCLUDE_DIR event.h
    /usr/local/include
    /usr/include
)

FIND_LIBRARY(LIBEVENT_LIBRARY event
    ${LIBEVENT_INCLUDE_DIR}/../lib64
    /usr/local/lib64
    /usr/lib64)

IF (LIBEVENT_INCLUDE_DIR AND LIBEVENT_LIBRARY)
    SET(LIBEVENT_FOUND TRUE)
ENDIF (LIBEVENT_INCLUDE_DIR AND LIBEVENT_LIBRARY)

IF (LIBEVENT_FOUND)
    MESSAGE(STATUS "Found LIBEVENT INCLUDE: ${LIBEVENT_INCLUDE_DIR}")
    MESSAGE(STATUS "Found LIBEVENT LIBRARY: ${LIBEVENT_LIBRARY}")
    SET(LIBEVENT_LIBRARIES ${LIBEVENT_LIBRARY})
ELSE (LIBEVENT_FOUND)
    IF (LIBEVENT_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "LIBEVENT not found")
    ELSE (LIBEVENT_FIND_REQUIRED)
        MESSAGE(STATUS "LIBEVENT not found")
    ENDIF (LIBEVENT_FIND_REQUIRED)
ENDIF (LIBEVENT_FOUND)

MARK_AS_ADVANCED(LIBEVENT_INCLUDE_DIR LIBEVENT_LIBRARY)
